import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SessionWrapper from "./SessionWrapper";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "ProofMint",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/logo.svg" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen bg-darkblue text-cream flex flex-col items-center justify-center p-6`}
      >
        <Header />
        <SessionWrapper>{children}</SessionWrapper> {/* ✅ wrapped here */}
        <footer className="mt-3 text-sm text-gray-500">
          Submission for NoirHack
        </footer>
      </body>
    </html>
  );
}
